/**
 * Generates the OpenCode plugin JS file content.
 *
 * OpenCode does not have built-in OTLP support like Claude Code or Codex.
 * Instead, we generate a self-contained JS plugin that hooks into
 * OpenCode's tool.execute.before/after and event callbacks, constructs
 * OTLP JSON log records (opencode.tool_call, opencode.token_usage events),
 * and POSTs them to agent-telemetry's /v1/logs endpoint.
 *
 * Ported from DCC's src/hooks/opencodePlugin.ts, with DCC-specific daemon
 * routes and metadata removed — only the OTLP log record construction and
 * POST logic is retained.
 */

/** Marker embedded in the generated file to identify agent-telemetry ownership. */
export const OPENCODE_PLUGIN_MARKER = '// Generated by agent-telemetry';

/** Plugin file name in ~/.config/opencode/plugins/ */
export const OPENCODE_PLUGIN_FILENAME = 'agent-telemetry.js';

/**
 * Generate the OpenCode plugin JS source code.
 * The endpoint is baked in at generation time.
 *
 * @param endpoint  agent-telemetry OTLP base endpoint (e.g. http://127.0.0.1:9911/api/otel)
 */
export function generateOpenCodePluginJS(endpoint: string): string {
  const base = endpoint.replace(/\/+$/, '');
  return `${OPENCODE_PLUGIN_MARKER} — do not edit manually
export const AgentTelemetryPlugin = async ({ directory, worktree }) => {
  const ENDPOINT = ${JSON.stringify(base)};
  let pendingToolUseId = "";
  let pendingToolStartTime = 0;
  const seenMessages = new Set();

  async function postOtlpLog(eventName, attrs) {
    try {
      await fetch(ENDPOINT + "/v1/logs", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          resourceLogs: [
            {
              resource: {
                attributes: [
                  { key: "service.name", value: { stringValue: "opencode" } },
                  { key: "engine.name", value: { stringValue: "opencode" } },
                ],
              },
              scopeLogs: [
                {
                  logRecords: [
                    {
                      timeUnixNano: String(Date.now() * 1e6),
                      attributes: [{ key: "event.name", value: { stringValue: eventName } }, ...attrs],
                    },
                  ],
                },
              ],
            },
          ],
        }),
      });
    } catch (_) {}
  }

  return {
    "event": async ({ event }) => {
      if (!event || event.type !== "message.updated") return;
      const info = event.properties && event.properties.info;
      if (!info || info.role !== "assistant" || !info.finish) return;
      const t = info.tokens;
      if (!t) return;
      const dedupKey = info.sessionID + "|" + info.id;
      if (seenMessages.has(dedupKey)) return;
      seenMessages.add(dedupKey);
      const tokenAttrs = [
        { key: "session.id", value: { stringValue: info.sessionID } },
        { key: "message_id", value: { stringValue: info.id } },
        { key: "model", value: { stringValue: info.modelID || "" } },
        { key: "provider_id", value: { stringValue: info.providerID || "" } },
        { key: "input_tokens", value: { intValue: t.input || 0 } },
        { key: "output_tokens", value: { intValue: t.output || 0 } },
        { key: "reasoning_tokens", value: { intValue: t.reasoning || 0 } },
        { key: "cache_read_tokens", value: { intValue: (t.cache && t.cache.read) || 0 } },
        { key: "cache_write_tokens", value: { intValue: (t.cache && t.cache.write) || 0 } },
        { key: "cost_usd", value: { stringValue: String(info.cost || 0) } },
      ];
      if (info.time && info.time.created && info.time.completed) {
        tokenAttrs.push({
          key: "duration_ms",
          value: { intValue: info.time.completed - info.time.created },
        });
      }
      await postOtlpLog("opencode.token_usage", tokenAttrs);
    },
    "tool.execute.before": async (input, output) => {
      pendingToolUseId =
        "opc-" + Date.now().toString(36) + "-" + Math.random().toString(36).slice(2, 8);
      pendingToolStartTime = Date.now();
    },
    "tool.execute.after": async (input, output) => {
      const mcpServer =
        (output.metadata && output.metadata.mcp && output.metadata.mcp.server) ||
        (output.metadata && output.metadata.mcp_server) ||
        "";
      const otlpAttrs = [
        { key: "session.id", value: { stringValue: input.sessionID || "" } },
        { key: "tool_name", value: { stringValue: input.tool } },
        { key: "tool_use_id", value: { stringValue: pendingToolUseId } },
        {
          key: "tool_input_size",
          value: { intValue: new TextEncoder().encode(JSON.stringify(input.args || {})).byteLength },
        },
        {
          key: "tool_result_size",
          value: { intValue: new TextEncoder().encode(output.output || "").byteLength },
        },
      ];
      if (mcpServer) otlpAttrs.push({ key: "mcp_server", value: { stringValue: mcpServer } });
      if (pendingToolStartTime) {
        otlpAttrs.push({ key: "duration_ms", value: { intValue: Date.now() - pendingToolStartTime } });
      }
      await postOtlpLog("opencode.tool_call", otlpAttrs);

      pendingToolUseId = "";
      pendingToolStartTime = 0;
    },
  };
};
`;
}
